project_id = "folwqawwrohkxhuksbgr"

[functions.send-email]
verify_jwt = false

[functions.request-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.promote-owner]
verify_jwt = true
